# Generated by Django 4.2.7 on 2023-11-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_aboutsidebar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('sosial_name', models.CharField(max_length=255, verbose_name='sosial media hesabi')),
                ('sosial_link', models.TextField(verbose_name='sosial media linki')),
            ],
            options={
                'verbose_name': 'sosial media hesabi',
                'verbose_name_plural': 'sosial media hesablari',
                'ordering': ('sosial_name',),
            },
        ),
    ]
