# Generated by Django 4.2.7 on 2023-11-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_sosialmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sosialmedia',
            name='sosial_name',
            field=models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('tiktok', 'Tiktok')], max_length=255, verbose_name='sosial media hesabi'),
        ),
    ]
