# Generated by Django 4.2.7 on 2023-11-16 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_sosialmedia_sosial_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sosialmedia',
            name='slug',
        ),
    ]
