# Generated by Django 4.2.7 on 2023-11-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_homeslider'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profesion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ixtisas'),
        ),
    ]
