# Generated by Django 4.2.7 on 2023-11-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_testimonial_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='slug',
        ),
    ]
