# Generated by Django 4.2.7 on 2023-11-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0014_remove_testimonial_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
