# Generated by Django 4.2.7 on 2023-11-17 18:03

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0016_emails_locations_phones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('logo', models.ImageField(upload_to=services.uploader.Uploader.upload_photo_to_logo)),
                ('logo_name', models.CharField(max_length=255, verbose_name='Right side of logo')),
                ('emails', models.ManyToManyField(to='my_app.emails', verbose_name='Emails')),
                ('locations', models.ManyToManyField(to='my_app.locations', verbose_name='Locations')),
                ('phones', models.ManyToManyField(to='my_app.phones', verbose_name='Phones')),
            ],
            options={
                'verbose_name': 'Main information',
                'verbose_name_plural': 'Main information',
                'ordering': ('-created_at',),
            },
        ),
    ]
