# Generated by Django 4.2.7 on 2023-11-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_maindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='is_part',
            field=models.BooleanField(default=False),
        ),
    ]
