# Generated by Django 4.2.5 on 2023-11-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0017_maindetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindetails',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='xerite'),
        ),
    ]
