# Generated by Django 4.2.5 on 2023-11-19 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_maindetails_map_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maindetails',
            name='map_url',
        ),
        migrations.AddField(
            model_name='contact',
            name='map_url',
            field=models.TextField(blank=True, null=True, verbose_name='xerite'),
        ),
    ]
