# Generated by Django 4.2.7 on 2023-11-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0018_locations_is_part'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='is_part',
        ),
        migrations.AddField(
            model_name='emails',
            name='is_part',
            field=models.BooleanField(default=False),
        ),
    ]
